# Generated by Django 4.2.23 on 2025-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_workinghours_max_appointments_per_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(30, '30 minutes'), (60, '60 minutes')], default=30),
        ),
    ]
